- name: install aws cli
  pip:
    name: awscli
    state: present

- name: Copy AWS config
  template:
    src: aws_cli_config.j2
    dest: '{{ home_path }}/.aws/config'


- name: Copy AWS CLI credentials
  template:
    src: aws_cli_credentials.j2
    dest: '{{ home_path }}/.aws/credentials'
